version: '2'
services:
  vibeville:
    image: tmokhele/vibeville:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      id: vibeville
  rabbitmq-user-registration:
    image: rabbitmq:management
    ports:
    - 15672:15672/tcp
    - 5672:5672/tcp
    labels:
      app: rabbitmq
      io.rancher.container.pull_image: always

