version: '2'
services:
  lb-vibeville:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 2
        protocol: http
        service: vibevileadmin
        source_port: 80
        target_port: 80
      - path: ''
        priority: 3
        protocol: http
        service: vibeville
        source_port: 8086
        target_port: 8086
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  vibeville:
    scale: 2
    start_on_create: true
  rabbitmq-user-registration:
    scale: 1
    start_on_create: true
